### ISSUE TITLE
Rename to WakuConnect

### ISSUE THREAD

**Issue by D4nte** [waku-org/js.waku.guide#11]
We are renaming DappConnect to WakuConnect

@jakubgs Could you please move this website from docs.dappconnect.dev to docs.wakuconnect.dev (the domain name has already been acquired).

**Comment by jakubgs** [comment]
We will need to transfer the domain ownership to our main Gandi account and set it up with CloudFlare.

**Comment by jakubgs** [comment]
Question, what about the old domain? should it just redirect?

**Comment by D4nte** [comment]
> Question, what about the old domain? should it just redirect?

Yes please, redirect.

**Comment by jakubgs** [comment]
Done: https://dev-docs.wakuconnect.dev/
Changes:
* https://github.com/vacp2p/docs.wakuconnect.dev/commit/412807bc - ci: move to docs.wakuconnect.dev domain
* https://github.com/status-im/infra-misc/commit/f9126d80 - sites: move dappconnect.dev to wakuconnect.dev
