### ISSUE TITLE
Deploy website using Jenkins CI

### ISSUE THREAD

**Issue by fryorcraken** [waku-org/js.waku.guide#63]
Deploy `master` on js.waku.guide
Deploy `develop` on dev-js.waku.guide.

**Comment by fryorcraken** [comment]
@jakubgs we migrated this repo around. It was previously deployed to docs.wakuconnect.dev

Can you please deploy to the new location as we are moving away from wakuconnect.dev?

**Comment by jakubgs** [comment]
You could at least make the title mean something.

**Comment by jakubgs** [comment]
Done:

- https://github.com/status-im/infra-misc/commit/edca8a6a - configure js.waku.guide and dev-js.waku.guide sites
- https://github.com/waku-org/js.waku.guide/commit/4adba002 - ci: change docs.wakuconnect.dev to js.waku.guide

Endpoints:

* https://js.waku.guide/
* https://dev-js.waku.guide/

Also old https://docs.wakuconnect.dev/ domain redirects to https://js.waku.guide/.

**Comment by fryorcraken** [comment]
@jakubgs thank you for that.

However I think there is an issue. `master` and `develop` have the same commits but the websites do not match (see the warning sign on the homepage)
https://js.waku.guide/
https://dev-js.waku.guide/

It seems that latest master did not get deployed on js.waku.guide. Indeed I can see an error in Jenkins: https://ci.infra.status.im/job/website/job/js.waku.org/

**Comment by fryorcraken** [comment]
I just did a push on both master and develop (8390b61248ad34cfb08c5003fc7b670a0d3239c8) but I can't see the CI being triggered in the Jenkins UI.

**Comment by jakubgs** [comment]
You're confusing builds for `js.waku.org` and `js.waku.guide`:

* https://ci.infra.status.im/job/website/job/js.waku.org/
* https://ci.infra.status.im/job/website/job/js.waku.guide/

The first one is failing due to changes to `package.json`, the latter is not starting.

**Comment by jakubgs** [comment]
Also dude, closing quotes is a good idea:
https://github.com/waku-org/js.waku.guide/blob/8390b61248ad34cfb08c5003fc7b670a0d3239c8/config.yaml#L14
```
+ hugo
Error: "/home/jenkins/workspace/website/js.waku.guide/config.yaml:14:1": failed to unmarshal YAML: yaml: line 14: did not find expected key
```

**Comment by jakubgs** [comment]
The webhook URL was wrong, also fixed the quote: https://github.com/waku-org/js.waku.guide/commit/3bd26bc6

* https://ci.infra.status.im/job/website/job/js.waku.guide/33/
* https://ci.infra.status.im/job/website/job/dev-js.waku.guide/81/

**Comment by fryorcraken** [comment]
I can see that `gh-page` branch is up to date but `js.waku.guide` is not so I am guessing an issue on GitHub pages now? Will push another commit see if it was a resolved outage.

**Comment by fryorcraken** [comment]
There's still an issue. Jobs looks good: https://ci.infra.status.im/job/website/job/js.waku.guide/34/
I can see that `gh-pages` contains the latest changes but it's not being deployed on https://js.waku.guide/

**Comment by fryorcraken** [comment]
The GitHub pages action says it's successful: https://github.com/waku-org/js.waku.guide/actions/runs/3433718458/jobs/5724336082

**Comment by fryorcraken** [comment]
The GitHub Page action says:

```
{"page_url":"http://js.waku.guide/","status_url":"https://api.github.com/repos/waku-org/js.waku.guide/pages/deployment/status/0be8182e46a6129b435480cf14c74e0b57508c31","preview_url":""}
Reported success!
```

the `page_url` is `http` and not `https`.
I can see that `http://js.waku.guide` returns a `301 Moved Permanently` to `https://js.waku.guide`.

```
▶ wget http://js.waku.guide
--2022-11-10 14:28:02--  http://js.waku.guide/
Resolving js.waku.guide (js.waku.guide)... 172.67.200.72, 104.21.68.243, 2606:4700:3033::6815:44f3, ...
Connecting to js.waku.guide (js.waku.guide)|172.67.200.72|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://js.waku.guide/ [following]
```

Maybe a red herring...
