### ISSUE TITLE
Impossible to navigate to other pages

### ISSUE THREAD

**Issue by AuHau** [waku-org/js.waku.guide#65]
If I navigate to the linked docs: [js.waku.guide](https://js.waku.guide/) then I can go to any other page than the homepage. Tried Chrome/Brave/Safari (latest versions) on macOS.

**Comment by alrevuelta** [comment]
Same can't navigate to any page using Firefox/macOs

**Comment by fryorcraken** [comment]
https://dev-js.waku.guide/ works fine so likely to be related to a deployment issue we already reported. Thanks for the report.

**Comment by fryorcraken** [comment]
Working towards a fix: https://github.com/waku-org/js.waku.guide/issues/63#issuecomment-1309113624

**Comment by fryorcraken** [comment]
Resolved, please be sure to force refresh your browser (ctrl+shift+r)
