### ISSUE TITLE
Research alternative docs site generator

### ISSUE THREAD

**Issue by jakubgs** [waku-org/js.waku.guide#7]
We need a site generator that provides built-in support for multiple languages.

Based on comments in https://github.com/rust-lang/mdBook/issues/5 it appears mdBook does not support that.

**Comment by jakubgs** [comment]
Based on the documentation from ReadTheDocs it appears this is not a simple static site generator:

>Read the Docs simplifies software documentation by building, versioning, and hosting of your docs, automatically. 
https://docs.readthedocs.io/en/stable/index.html

>The tutorial is aimed at people interested in learning how to use Read the Docs to host their documentation projects. 
https://docs.readthedocs.io/en/stable/tutorial/index.html

The ReadTheDocs service uses two possible static site generators: [Sphinx](https://docs.readthedocs.io/en/stable/intro/getting-started-with-sphinx.html) or [MkDocs](https://docs.readthedocs.io/en/stable/intro/getting-started-with-mkdocs.html)

**Comment by jakubgs** [comment]
This is a nice list of static site generators: https://jamstack.org/generators/

**Comment by jakubgs** [comment]
Some options I'm considering currently:

* https://gohugo.io/ - https://gohugo.io/content-management/multilingual/
* https://docusaurus.io/ - https://docusaurus.io/docs/i18n/introduction
* https://www.sphinx-doc.org/ - https://www.sphinx-doc.org/en/master/usage/advanced/intl.html
* https://www.mkdocs.org/ - https://www.mkdocs.org/user-guide/localizing-your-theme/ ([#2299](https://github.com/mkdocs/mkdocs/pull/2299))
* https://www.getzola.org/ - https://www.getzola.org/documentation/content/multilingual/
* https://docs.getpelican.com/ - https://docs.getpelican.com/en/latest/settings.html?highlight=lang#translations
* https://www.getnikola.com/ - https://www.getnikola.com/handbook.html#multilingual-posts

**Comment by jakubgs** [comment]
Hugo is VERY fast and provides several simple documentation templates:

* https://themes.gohugo.io/themes/hugo-book/
* https://themes.gohugo.io/themes/doks/
* https://themes.gohugo.io/themes/hugo-theme-docport/
* https://themes.gohugo.io/themes/hugo-theme-zdoc/

**Comment by jakubgs** [comment]
The most popular and cleanest one [hugo-book](https://github.com/alex-shpak/hugo-book) supports multiple languages:
https://github.com/alex-shpak/hugo-book#multi-language-support

**Comment by D4nte** [comment]
As commented in the PR, hugo looks great. Better than readthedocs and the multilang support is very neat/easy. Thanks for doing the research!

**Comment by jakubgs** [comment]
Since I've merged the Hugo changes I consider this done.
